Repository junye0l/openMind, pull requests merged in 2025-08, with the labels that each got.

#9 📝 docs : tailwind 버전 수정
  package-lock.json
  package.json
  postcss.config.js
  vite.config.js
Labels: 📖 Documentation

#32 bug : 각종 기초 세팅 버그 수정
  package-lock.json
  package.json
  src/components/mainpage/MainComponents.jsx
Labels: 🔥 Bug, 🧑🏻‍💻 FE

#33 feat : 질문 받기 및 질문 하러가기 버튼 기능 구현 및 브라우저 아이콘 추가
  index.html
  src/App.jsx
  src/assets/images/Main-icon.svg
  src/components/mainpage/MainComponents.jsx
  src/hooks/getsubjects.js
Labels: 📖 Doc, ✨ Feature, 🧑🏻‍💻 FE

#40 ✨ feat : 질문 대상 조회, 삭제 API 구조 구현 및 Axios 기본 구조 변경
  src/api/ApiAxios.js
  src/api/deleteSubjectsId.js
  src/api/getSubjectsId.js
Labels: ✨ Feature, 🧑🏻‍💻 FE

#55 📝 docs : motion 관련 오류 수정 및 메인페이지 파일 수정
  eslint.config.js
  src/components/mainpage/MainComponents.jsx
Labels: 📖 Doc, 🧑🏻‍💻 FE

#56 🎨 Style : svg 파일 svgr로 수정 & 메인페이지 post axios 에러 수정
  src/api/postSubjectsId.js
  src/components/AnswerList/Button.jsx
  src/components/AnswerList/LogoImg.jsx
  src/components/AnswerList/Select.jsx
  src/pages/Answer.jsx
  src/pages/AnswerList.jsx
Labels: ✨ Feature, 🧑🏻‍💻 FE, 🎨 Style

#60 💄 style : 메인페이지 SVGR로 구조 변경 및 시맨틱 태그를 이용한 SEO 최적화
  src/components/mainpage/MainComponents.jsx
Labels: ✨ Feature, 🧑🏻‍💻 FE, 🎨 Style

#63 [Style] 리스트 받은 질문 아이콘 svgr 변환 & 메인,리스트 버튼 컴포넌트화
  src/components/AnswerList/Button.jsx
  src/components/AnswerList/Card.jsx
  src/components/mainpage/MainComponents.jsx
  src/pages/AnswerList.jsx
Labels: 🧑🏻‍💻 FE, 🎨 Style

#66 답변하기 api 연동
  src/api/answers.js
  src/components/Answer/AnswerCard.jsx
  src/pages/Answer.jsx
Labels: ✨ Feature, 🧑🏻‍💻 FE

#68 feat : 질문 답변, 좋아요(싫어요) 버튼, URL복사, 공유하기 기능 구현
  index.html
  src/api/postReaction.js
  src/assets/images/main_bg.png
  src/assets/images/main_bg.svg
  src/components/question/Headers.jsx
  src/components/question/ProfileSection.jsx
  src/components/question/QuestionFeed/AnswerContent.jsx
  src/components/question/QuestionFeed/LikeButton.jsx
  src/components/question/QuestionFeed/Question.jsx
  src/components/question/QuestionFeed/QuestionCard.jsx
  src/components/question/QuestionFeed/QuestionCounter.jsx
  src/components/question/QuestionFeed/QuestionFeed.jsx
  src/components/question/QuestionFeedList.jsx
  src/components/question/ShareButton/CopyUrlButton.jsx
  src/components/question/ShareButton/FacebookShareButton.jsx
  src/components/question/ShareButton/KakaoShareButton.jsx
  src/components/question/Toast.jsx
  src/hook/useInfo.js
  src/hook/useQuestionList.js
  src/pages/AnserQuestion.jsx
  src/util/getPreviouslyTime.js
Labels: ✨ Feature, 🧑🏻‍💻 FE

#81 🐛 bug : 패키지 파일 수정 및 Answer.jsx 파일 수정
  package-lock.json
  package.json
  src/pages/Answer.jsx
Labels: 🔥 Bug, 🧑🏻‍💻 FE

#83 🐛 bug: 질문 자동 리렌더링 오류
  src/components/Modal/QuestionModal.jsx
Labels: 🔥 Bug, 🧑🏻‍💻 FE

#89 💄 style : main_bg 파일 최적화, alt 누락 작성, 좋아요 싫어요 색상 변경 수정
  src/components/Answer/LikeButtonViewOnly/LikeButtonViewOnly.jsx
  src/components/AnswerList/Card.jsx
  src/components/AnswerList/LogoImg.jsx
  src/components/AnswerList/Select.jsx
  src/components/mainpage/MainComponents.jsx
  src/components/question/Headers.jsx
  src/components/question/ProfileSection.jsx
Labels: 🧑🏻‍💻 FE, 🎨 Style

#95 ✨ feat : meta 태그 index.html 작성완료, 메타태그 이미지 파일 추가
  index.html
  src/assets/images/meta-img.png
Labels: ✨ Feature, 🧑🏻‍💻 FE

#120 답변하기 페이지 질문삭제 케밥버튼 구현
  src/api/getQuestion.js
  src/components/Answer/AnswerCard.jsx
  src/pages/Answer.jsx
Labels: ✨ Feature, 🧑🏻‍💻 FE
